before_script:
    - apt-get update && apt-get -qq install python-pip m4
    - pip install docker-squash
    - docker info
    - docker-squash --version
    - m4 --version

stages:
    - base
    - other

base:
    script:
        - ./docker-builder.sh build-image $CI_BUILD_NAME
#        - ./docker-builder.sh publish-image $CI_BUILD_NAME
    stage: base
#    only:
#        - master

nextcloud:
    script:
        - ./docker-builder.sh build-image $CI_BUILD_NAME
        - ./docker-builder.sh publish-image $CI_BUILD_NAME
    stage: other
#    only:
#        - master

